import { CreatorProfileOnMap } from '@/types/creator';

export const mockProfilesOnMap: CreatorProfileOnMap[] = [
  {
    id: '1',
    name: 'PRODUCER_X',
    roles: ['PRODUCER', 'ENGINEER'],
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    latitude: 34.0522,
    longitude: -118.2437,
    mainGenre: 'Hip-Hop',
    mainLink: 'https://open.spotify.com/artist/example',
    xp: 850,
  },
  {
    id: '2',
    name: 'STUDIO_WAVE',
    roles: ['STUDIO'],
    city: 'New York',
    state: 'NY',
    country: 'USA',
    latitude: 40.7128,
    longitude: -74.0060,
    mainGenre: 'R&B',
    studioName: 'Wave Studios NYC',
    mainLink: 'https://instagram.com/wavestudios',
    xp: 1200,
  },
  {
    id: '3',
    name: 'MC_FLOW',
    roles: ['ARTIST'],
    city: 'Atlanta',
    state: 'GA',
    country: 'USA',
    latitude: 33.7490,
    longitude: -84.3880,
    mainGenre: 'Trap',
    mainLink: 'https://open.spotify.com/artist/mcflow',
    xp: 650,
  },
  {
    id: '4',
    name: 'VISUAL_VIBE',
    roles: ['VISUAL_MEDIA', 'INFLUENCER'],
    city: 'Miami',
    state: 'FL',
    country: 'USA',
    latitude: 25.7617,
    longitude: -80.1918,
    mainGenre: 'Electronic',
    mainLink: 'https://instagram.com/visualvibe',
    xp: 420,
  },
  {
    id: '5',
    name: 'BEAT_LAB_BOSTON',
    roles: ['STUDIO', 'PRODUCER'],
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    latitude: 42.3601,
    longitude: -71.0589,
    mainGenre: 'Hip-Hop',
    studioName: 'Beat Lab Studios',
    mainLink: 'https://beatlabboston.com',
    xp: 980,
  },
  {
    id: '6',
    name: 'SOUL_SINGER_SAM',
    roles: ['ARTIST'],
    city: 'Nashville',
    state: 'TN',
    country: 'USA',
    latitude: 36.1627,
    longitude: -86.7816,
    mainGenre: 'Soul',
    mainLink: 'https://open.spotify.com/artist/soulsam',
    xp: 320,
  },
  {
    id: '7',
    name: 'ENGINEER_PRO',
    roles: ['ENGINEER'],
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    latitude: 41.8781,
    longitude: -87.6298,
    mainGenre: 'Rock',
    mainLink: 'https://instagram.com/engineerpro',
    xp: 1450,
  },
  {
    id: '8',
    name: 'MODEL_MAYA',
    roles: ['MODEL', 'INFLUENCER'],
    city: 'Las Vegas',
    state: 'NV',
    country: 'USA',
    latitude: 36.1699,
    longitude: -115.1398,
    mainGenre: 'Pop',
    mainLink: 'https://instagram.com/modelmaya',
    xp: 580,
  },
  {
    id: '9',
    name: 'INDIE_COLLECTIVE',
    roles: ['ARTIST', 'PRODUCER'],
    city: 'Portland',
    state: 'OR',
    country: 'USA',
    latitude: 45.5152,
    longitude: -122.6784,
    mainGenre: 'Indie',
    mainLink: 'https://open.spotify.com/artist/indiecollective',
    xp: 720,
  },
  {
    id: '10',
    name: 'MANAGER_MIKE',
    roles: ['MANAGER'],
    city: 'Seattle',
    state: 'WA',
    country: 'USA',
    latitude: 47.6062,
    longitude: -122.3321,
    mainGenre: 'Alternative',
    mainLink: 'https://instagram.com/managermike',
    xp: 890,
  },
  {
    id: '11',
    name: 'TRAP_HOUSE_STUDIO',
    roles: ['STUDIO'],
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    latitude: 29.7604,
    longitude: -95.3698,
    mainGenre: 'Trap',
    studioName: 'Trap House Studios',
    mainLink: 'https://traphousestudios.com',
    xp: 1100,
  },
  {
    id: '12',
    name: 'JAZZ_HANDS',
    roles: ['ARTIST', 'PRODUCER'],
    city: 'New Orleans',
    state: 'LA',
    country: 'USA',
    latitude: 29.9511,
    longitude: -90.0715,
    mainGenre: 'Jazz',
    mainLink: 'https://open.spotify.com/artist/jazzhands',
    xp: 1350,
  },
];
